
{:ssl-client-cert nil,
 :remote-addr "0:0:0:0:0:0:0:1",
 :scheme :http,
 :query-params {},
 :session
 {:cemerick.friend/identity
  {:current "admin",
   :authentications
   {"admin"
    {:identity "admin",
     :username "admin",
     :roles #{:tma-admin.server/admin}}}}},
 :cemerick.friend/auth-config
 {:default-landing-uri "/",
  :login-uri "/login",
  :credential-fn
  #<core$partial$fn__4190 clojure.core$partial$fn__4190@704f568>,
  :workflows
  [#<workflows$interactive_form$fn__12040 cemerick.friend.workflows$interactive_form$fn__12040@25d6fd1b>]},
 :context "/admin",
 :form-params {},
 :multipart-params
 {"file-1"
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-3612286536890354578.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  "created-at[month]" "4",
  "is-private" ["false" "true"],
  "file-2"
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-8570309787249228372.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  "community-item-name" "wpquestions",
  "file-3"
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-7513174250848717431.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  "machine-cookie-item-name" "",
  "refund-requested-date" "",
  "user-item-name" "wpquestions-sf_guard_user-3646",
  "created-at[day]" "12",
  "item-name" "wpquestions-question-2041",
  "end-at" "2011-04-15T08:26:00.000Z",
  "refund-request-explanation" "",
  "updated-at[m]" "15",
  "updated-at[year]" "2011",
  "updated-at[h]" "8",
  "this-user-is-disabled" "false",
  "subject" "CSS changes revert to default when dashboard change made",
  "refund-amount" "2",
  "previous-item-name" "",
  "admin-note" "",
  "created-at[ampm]" "am",
  "scheduled-for-deletion" "false",
  "status" "completed",
  "prize-amount" "10.0",
  "created-at[m]" "25",
  "updated-at[month]" "4",
  "item-type" "questions",
  "email-has-been-sent" "false",
  "session-id-when-question-was-created" "",
  "voting-starts" "",
  "updated-at[day]" "15",
  "submit" "Submit",
  "created-at[h]" "8",
  "refund-requested" "",
  "_id" "52a50cf4e4b04252e29f47be",
  "image" "",
  "description"
  "Complete newbie to WordPress and WordPress Questions. \r\n\r\nI am using a theme entitled Flexibility3 on WordPress. When I make changes to the CSS they render correctly on my site. If I subsequently make a change using the Flexibility3 dashboard it appears that the CSS reverts to the original default, all changes lost. \r\n\r\nIs this normal? Is there something I am doing wrong? Do all WordPress themes do this?\r\n\r\nthank you for any guidance,\r\n\r\nzoe",
  "created-at[year]" "2011",
  "start-at" "",
  "updated-at[ampm]" "am"},
 :request-method :post,
 :query-string nil,
 :route-params {},
 :content-type
 "multipart/form-data; boundary=----WebKitFormBoundary9zSz2rBeIgNPVsLQ",
 :cookies
 {"tma-admin-session" {:value "488a1a2e-f5a9-4580-bea5-435f91d9e2c1"}},
 :path-info "/process-input/",
 :uri "/admin/process-input/",
 :session/key "488a1a2e-f5a9-4580-bea5-435f91d9e2c1",
 :server-name "localhost",
 :params
 {:submit "Submit",
  :scheduled-for-deletion "false",
  "created-at[month]" "4",
  :status "completed",
  :subject "CSS changes revert to default when dashboard change made",
  :previous-item-name "",
  "created-at[day]" "12",
  "updated-at[m]" "15",
  :this-user-is-disabled "false",
  :is-private ["false" "true"],
  "updated-at[year]" "2011",
  :voting-starts "",
  "updated-at[h]" "8",
  :item-type "questions",
  :email-has-been-sent "false",
  :image "",
  :admin-note "",
  :refund-requested "",
  :end-at "2011-04-15T08:26:00.000Z",
  "created-at[ampm]" "am",
  :user-item-name "wpquestions-sf_guard_user-3646",
  "created-at[m]" "25",
  "updated-at[month]" "4",
  :refund-request-explanation "",
  :_id "52a50cf4e4b04252e29f47be",
  "updated-at[day]" "15",
  "created-at[h]" "8",
  :item-name "wpquestions-question-2041",
  :community-item-name "wpquestions",
  :file-2
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-8570309787249228372.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  :file-1
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-3612286536890354578.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  :refund-amount "2",
  :machine-cookie-item-name "",
  :refund-requested-date "",
  :session-id-when-question-was-created "",
  :file-3
  {:size 0,
   :tempfile
   #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-7513174250848717431.tmp>,
   :content-type "application/octet-stream",
   :filename ""},
  "created-at[year]" "2011",
  :description
  "Complete newbie to WordPress and WordPress Questions. \r\n\r\nI am using a theme entitled Flexibility3 on WordPress. When I make changes to the CSS they render correctly on my site. If I subsequently make a change using the Flexibility3 dashboard it appears that the CSS reverts to the original default, all changes lost. \r\n\r\nIs this normal? Is there something I am doing wrong? Do all WordPress themes do this?\r\n\r\nthank you for any guidance,\r\n\r\nzoe",
  "updated-at[ampm]" "am",
  :prize-amount "10.0",
  :start-at ""},
 :headers
 {"user-agent"
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.102 Safari/537.36",
  "cookie" "tma-admin-session=488a1a2e-f5a9-4580-bea5-435f91d9e2c1",
  "origin" "http://localhost:34000",
  "accept"
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "host" "localhost:34000",
  "referer"
  "http://localhost:34000/admin/edit/questions/wpquestions-question-2041",
  "content-type"
  "multipart/form-data; boundary=----WebKitFormBoundary9zSz2rBeIgNPVsLQ",
  "cache-control" "max-age=0",
  "accept-encoding" "gzip,deflate,sdch",
  "content-length" "5121",
  "accept-language" "en-US,en;q=0.8",
  "connection" "keep-alive"},
 :content-length 5121,
 :server-port 34000,
 :character-encoding nil,
 :body #<HttpInput org.eclipse.jetty.server.HttpInput@69217a79>}
 in monger/persist-this-item the item is: 
{:submit "Submit",
 :scheduled-for-deletion "false",
 :status "completed",
 :subject "CSS changes revert to default when dashboard change made",
 :previous-item-name "",
 :this-user-is-disabled "false",
 :is-private ["false" "true"],
 :voting-starts "",
 :item-type "questions",
 :email-has-been-sent "false",
 :image "",
 :admin-note "",
 :refund-requested "",
 :end-at "2011-04-15T08:26:00.000Z",
 :user-item-name "wpquestions-sf_guard_user-3646",
 :refund-request-explanation "",
 :_id "52a50cf4e4b04252e29f47be",
 :item-name "wpquestions-question-2041",
 :community-item-name "wpquestions",
 :file-2
 {:size 0,
  :tempfile
  #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-8570309787249228372.tmp>,
  :content-type "application/octet-stream",
  :filename ""},
 :file-1
 {:size 0,
  :tempfile
  #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-3612286536890354578.tmp>,
  :content-type "application/octet-stream",
  :filename ""},
 :refund-amount "2",
 :machine-cookie-item-name "",
 :refund-requested-date "",
 :session-id-when-question-was-created "",
 :file-3
 {:size 0,
  :tempfile
  #<File /var/folders/85/50nmp8fx3q72pxv4zlh_74pm0000gn/T/ring-multipart-7513174250848717431.tmp>,
  :content-type "application/octet-stream",
  :filename ""},
 :description
 "Complete newbie to WordPress and WordPress Questions. \r\n\r\nI am using a theme entitled Flexibility3 on WordPress. When I make changes to the CSS they render correctly on my site. If I subsequently make a change using the Flexibility3 dashboard it appears that the CSS reverts to the original default, all changes lost. \r\n\r\nIs this normal? Is there something I am doing wrong? Do all WordPress themes do this?\r\n\r\nthank you for any guidance,\r\n\r\nzoe",
 :prize-amount "10.0",
 :start-at ""}